name: Dump and Commit GitHub Profile Data

on:
  schedule:
    - cron: '0 * * * *' # Menjadwalkan tindakan ini setiap jam pada menit ke-0
  workflow_dispatch: # Memungkinkan tindakan ini dijalankan secara manual dari GitHub UI

jobs:
  collect-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up jq
      run: sudo apt-get install jq

    - name: Fetch GitHub profile data
      run: |
        USERNAME="indra87g"
        API_URL="https://api.github.com/users/${USERNAME}"
        curl -s $API_URL | jq -r '"Username: \(.login)\nName: \(.name)\nBio: \(.bio)\nLocation: \(.location)"' > profile_data.txt

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Commit and push profile_data.txt
      run: |
        git add profile_data.txt
        git commit -m "Update profile_data.txt with latest GitHub profile data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAS }}
