name: Render README

on:
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - name: Update README.md
      run: node index.js > README.md
    - name: Commit change & Push
      run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git add README.md
          git commit -am "docs: update README.md"
          git pull --rebase
          git push
